safe:        true

markdown:    kramdown
permalink:   /blog/:year/:month/:day/:title/

exclude: [".hyde.el", "_drafts"]

site:
    title : Junfeng Li
    description: Junfeng Li's weblog
    feedburner : http://feeds.feedburner.com/autozimu
    production_url: http://autozimu.github.io

author:
    name : Junfeng Li
    email : autozimu@gmail.com
    github : autozimu
    twitter : autozimu
