safe:        true
auto:        true
server:      true

markdown:    kramdown
pygments:    true
permalink:   /blog/:year/:month/:day/:title/

site:
    title : Matrix 42
    tagline: autozimu's weblog
    feedburner : feeds.feedburner.com/Matrix42

author:
    name : autozimu
    email : autozimu@gmail.com
    github : autozimu
    twitter : autozimu
