safe:        true

markdown:    kramdown
permalink:   /blog/:year/:month/:day/:title/

site:
    title : Matrix 42
    description: autozimu's weblog
    feedburner : http://feeds.feedburner.com/Matrix42
    production_url: http://autozimu.github.com

author:
    name : autozimu
    email : autozimu@gmail.com
    github : autozimu
    twitter : autozimu
