---
# Usage: http://ruhoh.com/usage/configure/

RuhohSpec: '1.0'
theme : dinky
production_url : http://autozimu.github.com

posts:
  permalink: /:year/:month/:day/:title
  summary_lines: 10
  latest: 10

pages:
  permalink: 'pretty'
