title : Matrix 42
tagline: autozimu's weblog
author :
  name : autozimu
  email : autozimu@gmail.com
  github : autozimu
  twitter : autozimu
  feedburner : autozimu.github.com # FIXME

navigation :
  - archive.html
  - categories.html
  - tags.html
  - links.md
  - about.md
