title : autozimu
tagline: autozimu's web log
author :
  name : autozimu
  email : autozimu@gmail.com
  github : autozimu
  twitter : autozimu
  feedburner : autozimu.github.com # FIXME

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md

